---
- name: Verify supported operating system
  ansible.builtin.assert:
    that:
      - ansible_facts['distribution'] in supported_os_distribution
    fail_msg: >-
      This deployproxy role supports
      {{ supported_os_distribution | join(', ') }} only.

- name: Ensure proxy drop-in directory exists
  ansible.builtin.file:
    path: "{{ deployproxy_dropin_dir }}"
    state: directory
    owner: root
    group: deployer
    mode: "2775"

- name: Install proxy deployment CLI script
  ansible.builtin.template:
    src: deployproxy.j2
    dest: "{{ deployproxy_cli_path }}"
    owner: root
    group: root
    mode: "0755"
