---
- name: Reload Caddy
  ansible.builtin.systemd:
    name: "{{ caddy_service_name }}"
    state: reloaded
  when: not ansible_check_mode

- name: Restart Caddy watcher
  ansible.builtin.systemd:
    name: "{{ caddy_watch_service_name }}"
    state: restarted
    daemon_reload: true
  when: not ansible_check_mode
