---
- name: Ensure deployment engine dependencies are installed
  ansible.builtin.package:
    name:
      - curl
      - python3
      - tar
    state: present

- name: Install deployment engine
  ansible.builtin.template:
    src: deploy.j2
    dest: "{{ deployment_engine_path }}"
    owner: "{{ deployment_engine_owner }}"
    group: "{{ deployment_engine_group }}"
    mode: "{{ deployment_engine_mode }}"
