# =============================================================================
# Ansible Inventory
# =============================================================================
# Group   : [servers]
# Purpose : All servers managed by this Ansible project.
[servers]
server-name ansible_host=hostname
server-name ansible_host=hostname

[servers:vars]
ansible_user=ansible-user
