---
- name: Load audit rules
  ansible.builtin.command:
    cmd: augenrules --load
  check_mode: false
  register: auditd_augenrules_result
  changed_when: "'changed' in auditd_augenrules_result.stdout"
