---
ssh_hardening_port: 22

ssh_hardening_permit_root_login: "no"

ssh_hardening_password_authentication: "no"

ssh_hardening_pubkey_authentication: "yes"

ssh_hardening_kbdinteractive_authentication: "no"

ssh_hardening_allow_users:
  - "{{ ansible_user }}"
  - sysadmin
  - automation
