---
- name: Verify supported operating system
  ansible.builtin.assert:
    that:
      - ansible_facts['distribution'] in supported_os_distribution
    fail_msg: >-
      This apparmor role supports
      {{ supported_os_distribution | join(', ') }} only.

- name: Install AppArmor packages
  ansible.builtin.apt:
    name:
      - apparmor
      - apparmor-utils
    state: present
    update_cache: true
  when: apparmor_enabled

- name: Ensure AppArmor service is enabled and started
  ansible.builtin.service:
    name: apparmor
    enabled: true
    state: started
  when: apparmor_enabled

- name: Verify AppArmor is enabled
  ansible.builtin.command:
    cmd: aa-enabled
  register: apparmor_status
  changed_when: false
  failed_when: apparmor_status.rc != 0
  when: apparmor_enabled
