---
- name: Verify supported operating system
  ansible.builtin.assert:
    that:
      - ansible_facts['distribution'] == "Ubuntu"
    fail_msg: "This auto_updates role supports Ubuntu only."

- name: Ensure unattended-upgrades is installed
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true

- name: Configure APT automatic updates
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Configure unattended-upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Validate unattended-upgrades configuration
  ansible.builtin.command:
    cmd: unattended-upgrade --dry-run
  changed_when: false
  check_mode: false
  when: auto_updates_enabled
